In [2]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
a=[1,2,3]
print(arr+10)

[11 12 13 14 15]


In [5]:
print(arr+10)

[11 12 13 14 15]


In [6]:
#0-D ARRAY
arr0 =np.array(1)
print(arr0)

1


In [10]:
#1-D ARRAY
arr1 =np.array([1,2,3])
print(arr1)

[1 2 3]


In [14]:
#2-D ARRAY
arr2 =np.array([[1,2,3],[1,2,3]])
print(arr2)

[[1 2 3]
 [1 2 3]]


In [18]:
#3-D ARRAY
arr3 =np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [20]:
#check dimension of array

arr3.ndim

3

In [21]:
arr2.ndim

2

In [26]:
#joining arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[1 2 3 4 5 6]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
#Stacking
arr1=np.array([2,4,6])
arr2=np.array([8,6,4])
arr = np.stack((arr1,arr2), axis =1)    
print(arr)

[[2 8]
 [4 6]
 [6 4]]


In [32]:
#HorizontalStacking
arr1=np.array([2,4,6])
arr2=np.array([8,6,4])
arr = np.hstack((arr1,arr2))
print(arr)

[2 4 6 8 6 4]


In [33]:
#verticalStacking
arr1=np.array([2,4,6])
arr2=np.array([8,6,4])
arr = np.vstack((arr1,arr2))
print(arr)

[[2 4 6]
 [8 6 4]]


In [34]:
a=5
print(a*a)

25


In [35]:
print(np.sqrt(a))

2.23606797749979


In [36]:
print(np.sqrt(a*a*a))

11.180339887498949


In [37]:
print(np.log(a))

1.6094379124341003
